import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// 打包产物统一放到 dist/，dist 本身就是可直接安装的插件目录
const DIST = "dist";
const ASSETS = ["manifest.json", "styles.css"];

const copyAssets = {
	name: "copy-assets",
	setup(build) {
		build.onEnd(() => {
			fs.mkdirSync(DIST, { recursive: true });
			ASSETS.forEach((name) => fs.copyFileSync(name, path.join(DIST, name)));
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	plugins: [copyAssets],
	platform: "browser",
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(DIST, "main.js"),
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await context.dispose();
	console.log(`构建完成 → ${path.join(DIST, "main.js")}`);
} else {
	await context.watch();
}
